name: Backend Tests Workflow

on:
  workflow_run:
    workflows: ["Marketplace workflow"]
    types:
      - completed

jobs:
  build:
    name: Build
    environment: dev
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Print event
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Code Fetch
        uses: actions/checkout@v3
        ref: github.event.workflow_run.head_branch

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Cache Fetch
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-modules-
            ${{ runner.os }}-yarn-

      - name: Install modules
        run: yarn install
