name: Backend Tests Workflow

on: workflow_call

jobs:
  build:
    name: Build
    environment: dev
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Code Fetch
        uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Cache Fetch
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-modules-
            ${{ runner.os }}-yarn-

      - name: Install modules
        run: yarn install
