# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Marketplace workflow

on:
  pull_request:
    branches: [main]
    types: [opened, closed, reopened, synchronize]
  merge_group:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel 
jobs:
  build:
    name: Build
    environment: dev
    if: ${{ !(github.event.pull_request.merged == false && github.event.action == 'closed') }}
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Code Fetch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Cache Fetch
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-modules-
            ${{ runner.os }}-yarn-

      - name: Install modules
        run: yarn install

  backend-tests:
    if: ${{ !(github.event.pull_request.merged == false && github.event.action == 'closed') }}
    uses: ./.github/workflows/backend_tests.yml
