name: Rollback Workflow

on:
  workflow_dispatch:
    inputs:
      STAGE:
        description: 'Environment'
        required: true
        default: 'staging'
        type: choice
        options:
        - prod
        - staging
        - dev
      APPS:
        description: 'App (all apps should be deployed by default)'
        type: choice
        default: 'all'
        options:
        - all
        - landonline-ui
        - platform
      FROM_TAG:
        description: 'From tag'
        required: true
      TO_TAG:
        description: 'To tag'
        required: true

jobs:
  handle-tag:
    name: Handle tags
    runs-on: ubuntu-latest
    outputs:
      ROLLBACK_DIRECTION: ${{ steps.get-versions.outputs.ROLLBACK_DIRECTION }}
      VERSIONS: ${{ steps.get-versions.outputs.VERSIONS }}
    steps:
      - name: Code Fetch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Versions
        id: get-versions
        run: |
          version() { echo "$@" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'; }

          if [ $(version "${{ inputs.FROM_TAG }}") -ge $(version "${{ inputs.TO_TAG }}") ]; then
            VERSIONS=`git tag -l | awk -v FROM_TAG=${{ inputs.FROM_TAG }} -v TO_TAG=${{ inputs.TO_TAG }} 'version $0 <= version FROM_TAG && version $0 > version TO_TAG {print$1}' | awk '{a[i++]=$0} END {for (j=i-1; j>=0;) print a[j--] }'`
            echo "::set-output name=ROLLBACK_DIRECTION::down"
            echo "::set-output name=VERSIONS::$VERSIONS"
          else
            VERSIONS=`git tag -l | awk -v FROM_TAG=${{ inputs.FROM_TAG }} -v TO_TAG=${{ inputs.TO_TAG }} 'version $0 >= version FROM_TAG && version $0 < version TO_TAG {print$1}'`
            echo "::set-output name=ROLLBACK_DIRECTION::up"
            echo "::set-output name=VERSIONS::$VERSIONS"
          fi

          echo "ROLLBACK_DIRECTION: $ROLLBACK_DIRECTION"
          echo "VERSIONS: $VERSIONS"

  roll-back:
    environment: ${{ inputs.STAGE }}
    needs: [handle-tag]
    name: Rollback
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Code Fetch
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.TO_TAG }}
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Cache Fetch
        uses: actions/cache@v3
        with:
          path: |
            '**/node_modules'
            .netlify/cache
          key: ${{ runner.os }}-modules-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install modules
        run: yarn install

      - name: Migration
        if: contains('platform, all', inputs.APPS)
        run: |
          echo "VERSIONS $VERSIONS"

          for CURRENT_TAG in $VERSIONS
          do
            ROLLBACK_DIRECTION=$ROLLBACK_DIRECTION CURRENT_TAG=$CURRENT_TAG STAGE=$STAGE bash ./ops/migrate.sh
          done
        env:
          ROLLBACK_DIRECTION: ${{ needs.handle-tag.outputs.ROLLBACK_DIRECTION }}
          VERSIONS: ${{ needs.handle-tag.outputs.VERSIONS }}
          STAGE: ${{ inputs.STAGE }}
