name: Rollback Workflow

on:
  workflow_dispatch:
    inputs:
      STAGE:
        description: 'Environment'
        required: true
        default: 'staging'
        type: choice
        options:
        - prod
        - staging
        - dev
      APPs:
        description: 'App (all apps should be deployed by default)'
        type: choice
        default: 'all'
        options:
        - all
        - landonline-ui
        - platform
      TAG:
        description: 'Tag'
        required: true

jobs:
  roll-back:
    name: Rollback
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Code Fetch
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.TAG }}
          fetch-depth: 0

      - run: bash ops/file.sh

      - name: DEPLOY platform
        if: contains('platform, all', inputs.APPS)
        run: echo "Platform is being deployed"

      - name: DEPLOY landonline-ui
        if: contains('landonline-ui, all', inputs.APPS)
        run: echo "Landnow is being deployed"
